name: Zenodo speedtest on runner

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  AddData:
    runs-on: nrec-large
    environment: user_data_addition
    timeout-minutes: 1440
    container:
      image: nmrlipids/core
      options: --user root
    env:
      FMDL_DATA_PATH: ${{ github.workspace }}/BilayerData
      MEM_CUTOFF: 1500000000

    steps:
      - name: Install speedtest-cli
        run: |
          apt-get update
          apt-get install -y speedtest-cli

      - name: Run speedtest in job container
        run: |
          speedtest-cli --simple
      - name: Download via host docker (nmrlipids/core)
        run: |
          sudo docker run --rm \
            --user root \
            -v /persistent01:/persistent01 \
            nmrlipids/core \
            bash -lc '
              apt-get update &&
              apt-get install -y wget &&
              cd /persistent01 &&
              wget -4 -O production_ci_hostdocker.xtc "https://zenodo.org/records/10261345/files/production.xtc?download=1"
            '
      
