name: Zenodo speedtest on runner

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  speedtest:
    runs-on: nrec-large
    timeout-minutes: 120

    steps:
      - name: Show host + persistent01 info
        run: |
          echo "Host: $(hostname)"
          echo
          echo "pwd: $(pwd)"
          df -h /
          df -h /persistent01 || true
          ls -al /persistent01 || true

      - name: Download via host docker (nmrlipids/core)
        run: |
          sudo docker run --rm \
            -v /persistent01:/persistent01 \
            nmrlipids/core \
            bash -lc '
              apt-get update &&
              apt-get install -y wget &&
              wget -4 -O production_ci_hostdocker.xtc "https://zenodo.org/records/10261345/files/production.xtc?download=1"
            '
      
