name: Process info file from pull request

permissions:
  contents: read

on:
  pull_request_target:
    types: [opened]
    paths:
      - 'UserData/**'
jobs:
  AddData:
    if: "${{ github.event.pull_request.head.repo.full_name == 'MagnusSletten/BilayerData' && github.repository == 'MagnusPriv/BilayerData' }}"
    runs-on: nrec-large
    timeout-minutes: 1440
    container:
      image: nmrlipids/core
      options: --user 1000:1000
    env:
      NMLDB_DATA_PATH: ${{ github.workspace }}/BilayerData
      NMLDB_SIMU_PATH: ${{ github.workspace }}/BilayerData/Simulations
    steps:
      - name: Checkout BilayerData
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: BilayerData
          persist-credentials: false

      - name: Checkout Databank
        uses: actions/checkout@v4
        with:
          repository: MagnusSletten/Databank
          ref: workflow-update
          path: Databank

      - name: Run dry run of AddData 
        env:
          TQDM_DISABLE: True
        working-directory: Databank
        run: |
          pip install -e . -r ./Scripts/DatabankLib/requirements.txt
          python Scripts/WorkflowScripts/ProcessInfoFile.py \
            --info_file_path ../BilayerData/UserData/info.yml --dry_run
